---
title: "Repeat history"
author: "Don Boyd"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 4
---


```{r runall, eval=FALSE, echo=FALSE}
# When we want a final report, run the following code selectively "by hand" (interactively) -- NEVER using Knit with eval=TRUE

rmdfn <- "./_main.rmd" # this file
outfn <- paste0("Results/", "RepeatHistory_", format(Sys.time(), "%Y-%m-%d"), ".html")
rmarkdown::render(rmdfn, output_format="html_document", output_file=outfn)

# Note that it is safest to fully exit RStudio and restart it before running the whole thing. Otherwise knitr can get confused
# and include repetitive information in the output html file.

```


```{r mainSet options, echo=FALSE, cache=FALSE}
options(width=120)
knitr::opts_chunk$set(fig.width=14, fig.height=10, echo=FALSE)
# Note: when saving maps (ggsave), width=16, height=9 seems to get rid of white space

# NOTE: Don't put ANYTHING in child code blocks - it won't be run! Even a comment will generate a warning

```


```{r defines}

# devtools::install_github("donboyd5/pdata")
# define directories where needed data are stored (other than rdat, which is always defined)

datd <- "./Data/"
resd <- "./Results/"
 
```


```{r loads, message=FALSE}
library("ggplot2")
library("scales") # so we can use scales with ggplot2
library("plyr") # needed for ddply; must be loaded BEFORE dplyr
library("reshape2")
library("magrittr")
library("tidyr")
library("dplyr") # always load AFTER plyr
options(dplyr.print_min = 60) # default is 10
options(dplyr.print_max = 60) # default is 20
library("knitr")
library("lubridate")
library("stringr")
library("grDevices")
library("readr")
library("readxl")

library("btools") # library that I created (install from github)
library("bdata")
library("pdata")

library("fof")
library("apitools")

# sessionInfo()
# devtools::install_github("donboyd5/fof")

```


```{r functions}
p25 <- function(x) quantile(x, .25, na.rm=TRUE, names=FALSE)
p75 <- function(x) quantile(x, .75, na.rm=TRUE, names=FALSE)
iqr <- function(x) p75(x) - p25(x) # use IQR instead

```


```{r statemapsetup, eval=FALSE, warning=FALSE}
# supress warnings that we'll get from windowsFonts
# Lucida Sans Typewriter is a monspace font, and I want a good monospace font for maps
windowsFonts(mono2=windowsFont("TT Lucida Sans Typewriter")) # default mono is Courier - associate mono2 with my preferred monospace 

map48 <- map_data("state")
map48$stabbr <- as.character(factor(map48$region, levels=tolower(stcodes$stname), labels=stcodes$stabbr))
# ht(map48)

# construct data frame with state centers and stabbr to annotate the map
# with a dummy group variable on the file so ggplot does not get confused, since we are using group in these maps
stabbrmaplabels <- data.frame(state.center, stabbr=state.abb, group=1) %>%
  filter(!stabbr %in% c("AK", "HI"))

```


```{r datasetup}

# add any desired variables here
ppd <- ppd # so that we can look at it in the viewer pane

# get and save a trimmed version of the fof file as it sometimes gives trouble - then read the saved file in
# uncomment this to create the file
# from the fof package
# exclude description as it seems to be giving trouble
# z1 <- fof
# z1vars <- count(z1, variable, description)
# saveRDS(z1vars, paste0(datd, "z1vars.rds"))

# now construct a revised z1 in steps because of all of the trouble
# converting to data frame seems key to fixing data corruption problem
z1 <- as.data.frame(fof) %>%
  filter(freq=="A") %>%
  mutate(snamex=str_sub(variable, 1, -3)) %>%
  mutate(year=year(date)) %>% 
  select(-freq, -date)

# get gdp price index to adjust for price changes over time and create a fiscal year value that approximates the typical state fiscal year
gdppi <- FRED("gdppi.a") %>%
  mutate(value.fy=(value + lag(value)) / 2)

# also, get real GDP
rgdp <- FRED("rgdp.a") %>% select(year, variable=series, rvalue=value) %>% # rvalue means real value
  arrange(year) %>%
  mutate(rvalue.fy=(rvalue + lag(rvalue)) / 2 ) %>%
  filter(year>=1970)

# set up the data
# note that this is state govt taxes only; may need to come back and think about local, but not yet
tax <- sgtax.a %>% filter(vname %in% c("tottax", "iit", "gst"), stabbr=="US", year>=1970) %>%
  select(vname, year, value) %>%
  spread(vname, value) %>%
  mutate(other=tottax - naz(iit) - naz(gst)) %>%
  gather(variable, value, -year) %>% 
  # construct real value - 2014 dollars
  mutate(rvalue=value * gdppi$value.fy[match(2014, gdppi$year)] / gdppi$value.fy[match(year, gdppi$year)])
# tax %>% select(-value) %>% spread(variable, rvalue) %>% kable(caption="Check: Real SG tax revenue", digits=0)

```


```{r childPensions, child="childPensions.rmd", eval=TRUE}
```


```{r childTaxes, child="childTaxes.rmd", eval=TRUE}
```


```{r childIncomeTax, child="childIncomeTax.rmd", eval=TRUE}
```


```{r childSalesTax, child="childSalesTax.rmd", eval=TRUE}
```


```{r childOtherTax, child="childOtherTax.rmd", eval=TRUE}
```


```{r childInvestReturns, child="childInvestReturns.rmd", eval=TRUE}
```


```{r childPullAllTogether, child="childPullAllTogether.rmd", eval=TRUE}
```




